[env]
TERM="ixterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[window]
# padding.y = 1
# padding.x = 1 
decorations = "Buttonless"
opacity = 0.6
blur= true

[font]
normal.family="MesloLGS Nerd Font Mono"
size = 12
