[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM="ixterm-256color"

[window]
# padding.y = 1
# padding.x = 1 
decorations = "Buttonless"
opacity = 0.95
blur= true

[font]
normal.family="MesloLGS Nerd Font Mono"
size = 12
