[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[env]
TERM="ixterm-256color"

[window]
# padding.y = 1
# padding.x = 1 
decorations = "Buttonless"
opacity = 0.95
blur= true

[font]
# normal.family="MesloLGS Nerd Font Mono"
# normal.family="FireCode Nerd Font Mono"
normal.family="Hack Nerd Font Mono"
size = 10
