[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[env]
TERM="xterm-256color"

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 0.5 
blur= true
dimensions = { columns=70, lines=25 }

[font]
normal.family="Hack Nerd Font Mono"
size = 14

[cursor]
style.shape="Block"
style.blinking="Never"
thickness=1.0
unfocused_hollow=true

[colors]
cursor= { text = "#181818", cursor = "#8e8e8e" }

[terminal]
shell = { program = "/usr/local/bin/tmux", args = ["new-session"] }



