-- -- -- plugins/quarto.lua
return {}
-- return {
-- 	{
-- 		"quarto-dev/quarto-nvim",
-- 		dependencies = {
-- 			"jmbuhr/otter.nvim",
-- 			"nvim-treesitter/nvim-treesitter",
-- 			"jpalardy/vim-slime",
-- 		},
-- 		config = function()
-- 			require("quarto").setup({
-- 				debug = false,
-- 				closePreviewOnExit = true,
-- 				lspFeatures = {
-- 					enabled = true, -- Enable LSP features
-- 					chunks = "curly",
-- 					languages = { "python" }, -- Only enable Python for now
-- 					hover = {
-- 						enabled = true,
-- 					},
-- 					definition = {
-- 						enabled = true,
-- 					},
-- 					diagnostics = {
-- 						enabled = true,
-- 						triggers = {}, -- Linting triggered on save
-- 					},
-- 					completion = {
-- 						enabled = true, -- Enable autocompletion
-- 					},
-- 				},
-- 				codeRunner = {
-- 					enabled = false, -- Disable the code running feature
-- 				},
-- 			})
-- 		end,
-- 	},
-- }
